project_name: ping42-admin-api
version: 2

# setups builds for linux and darwin on amd64 and arm64
# https://goreleaser.com/customization/build
builds:
- env:
  goos:
  - linux
  goarch:
  - amd64
  # ensures mod timestamp to be the commit timestamp
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    # trims path
    - -trimpath
  ldflags:
    # use commit date instead of current date as main.date
    # only needed if you actually use those things in your main package, otherwise can be ignored.
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
  id: "admin-api"
  binary: "admin-api"

# Note: this should be true only on public repos
# proxies from the go mod proxy before building
# https://goreleaser.com/customization/gomod
gomod:
  proxy: false

# config the checksum filename
# https://goreleaser.com/customization/checksum
checksum:
  name_template: 'checksums.txt'

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# create a docker image
# https://goreleaser.com/customization/docker
dockers:
- id: "ping42-admin-api"
  image_templates:
    - 'ghcr.io/ping-42/admin-api:{{ .Version }}'
    - 'ghcr.io/ping-42/admin-api:latest'
  dockerfile: Dockerfile
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.description=PING42 Admin API for Apps"